### PR TITLE
Documentation cleanup and adding docker commands and badge

### PR DESCRIPTION
**Pull request by ctoestreich**
* Docker commands
* Docker badge
* Cleanup pages with bad links

### CODE REVIEW

**Comment by brianwyka** [comment]
Build is failing @ctoestreich.  Broken Docusaurus links...

**Comment by ctoestreich** [comment]
@brianwyka  @PseudoCoding  who can approve these things these days?

**Comment by PseudoCoding** [comment]
I cannot anymore

**Comment by brianwyka** [comment]
We may be in some weird limbo state.

**Comment by amyschoen** [comment]
Any of the three of you should be able to approve.  I left you all with write access when you left the company.  Since I'm here now, I'll take a look and get you approved.

**Review by amyschoen — APPROVED** [review]
👍  Looks good

**Comment by amyschoen** [comment]
Oh...Interesting.  We are in limbo.  I'll clean up the CODEOWNERS and then get this merged in.

**Comment by amyschoen** [comment]
@ctoestreich, you should be all good to merge when ready.  I updated CODEOWNERS to include the Optum org owners as well as the sourcehawk team.

**Review by amyschoen — APPROVED** [review]
👍

**Pull request merged**
